[package]
name = "xrf-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.53", features = ["derive", "default"] }
colored = "3.0.0"
ddsfile = "0.5.2"
env_logger = "0.11.8"
log = "0.4.28"
tokio = { version = "1.48.0", features = ["full"] }
xray-archive = { path = "../../crates/xray-archive" }
xray-db = { path = "../../crates/xray-db" }
xray-gamedata = { path = "../../crates/xray-gamedata" }
xray-ltx = { path = "../../crates/xray-ltx" }
xray-error = { path = "../../crates/xray-error" }
xray-texture = { path = "../../crates/xray-texture" }
xray-translation = { path = "../../crates/xray-translation" }
xray-utils = { path = "../../crates/xray-utils" }

[lints]
workspace = true