[package]
name = "xray-error"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.9"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.17"
xray-error-derive = { path = "../xray-error-derive" }

[lints]
workspace = true