[package]
name = "xray-error-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.10.0"
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = "2.0.111"

[lints]
workspace = true